// Generated by gencpp from file serial_node_pkt/serial_massage.msg
// DO NOT EDIT!


#ifndef SERIAL_NODE_PKT_MESSAGE_SERIAL_MASSAGE_H
#define SERIAL_NODE_PKT_MESSAGE_SERIAL_MASSAGE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace serial_node_pkt
{
template <class ContainerAllocator>
struct serial_massage_
{
  typedef serial_massage_<ContainerAllocator> Type;

  serial_massage_()
    : data()
    , data_two()  {
    }
  serial_massage_(const ContainerAllocator& _alloc)
    : data(_alloc)
    , data_two(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_type;
  _data_type data;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _data_two_type;
  _data_two_type data_two;





  typedef boost::shared_ptr< ::serial_node_pkt::serial_massage_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::serial_node_pkt::serial_massage_<ContainerAllocator> const> ConstPtr;

}; // struct serial_massage_

typedef ::serial_node_pkt::serial_massage_<std::allocator<void> > serial_massage;

typedef boost::shared_ptr< ::serial_node_pkt::serial_massage > serial_massagePtr;
typedef boost::shared_ptr< ::serial_node_pkt::serial_massage const> serial_massageConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::serial_node_pkt::serial_massage_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::serial_node_pkt::serial_massage_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace serial_node_pkt

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'serial_node_pkt': ['/home/wwl/chassis/src/serial_node_pkt/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::serial_node_pkt::serial_massage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::serial_node_pkt::serial_massage_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_node_pkt::serial_massage_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::serial_node_pkt::serial_massage_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_node_pkt::serial_massage_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::serial_node_pkt::serial_massage_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::serial_node_pkt::serial_massage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8fd29414c00de9e0c5d9c3a1ce7ea153";
  }

  static const char* value(const ::serial_node_pkt::serial_massage_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8fd29414c00de9e0ULL;
  static const uint64_t static_value2 = 0xc5d9c3a1ce7ea153ULL;
};

template<class ContainerAllocator>
struct DataType< ::serial_node_pkt::serial_massage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "serial_node_pkt/serial_massage";
  }

  static const char* value(const ::serial_node_pkt::serial_massage_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::serial_node_pkt::serial_massage_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string data\n\
string data_two\n\
";
  }

  static const char* value(const ::serial_node_pkt::serial_massage_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::serial_node_pkt::serial_massage_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.data);
      stream.next(m.data_two);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct serial_massage_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::serial_node_pkt::serial_massage_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::serial_node_pkt::serial_massage_<ContainerAllocator>& v)
  {
    s << indent << "data: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data);
    s << indent << "data_two: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.data_two);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SERIAL_NODE_PKT_MESSAGE_SERIAL_MASSAGE_H
